// Константы для размеров и отступов
export const TREE_CONSTANTS = {
  PERSON_WIDTH: 200,
  PERSON_HEIGHT: 140,
  VERTICAL_GAP: 140,
  HORIZONTAL_GAP: 50,
  BRANCH_GAP: 120,
  MIN_SCALE: 0.3,
  MAX_SCALE: 2,
  ZOOM_FACTOR: 1.1, // Как в рабочем примере
  DRAG_THRESHOLD: 5,
};

// Стили для компонентов
export const STYLES = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    minHeight: '100vh',
    backgroundColor: '#f9fafb',
    padding: '1rem',
  },
  title: {
    fontSize: '1.875rem',
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: '1rem',
  },
  svgContainer: {
    width: '100%',
    height: '80vh',
    overflow: 'hidden',
    backgroundColor: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    position: 'relative',
    marginBottom: '1rem',
  },
  activeMode: {
    position: 'absolute',
    top: '0.5rem',
    right: '0.5rem',
    backgroundColor: '#fef3c7',
    color: '#92400e',
    padding: '0.25rem 0.5rem',
    borderRadius: '0.25rem',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    zIndex: 10,
    fontSize: '0.875rem',
  },
  notification: {
    position: 'fixed',
    top: '20px',
    right: '20px',
    backgroundColor: '#ef4444',
    color: 'white',
    padding: '10px 20px',
    borderRadius: '6px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.2)',
    zIndex: 100,
    opacity: 1,
    transition: 'opacity 0.3s ease',
  },
  buttonsContainer: {
    display: 'flex',
    gap: '1rem',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: '1rem',
  },
  button: {
    padding: '0.5rem 1rem',
    borderRadius: '0.375rem',
    cursor: 'pointer',
    border: 'none',
    fontWeight: '500',
  },
  greenButton: {
    backgroundColor: '#059669',
    color: 'white',
  },
  purpleButton: {
    backgroundColor: '#7c3aed',
    color: 'white',
  },
  blueButton: {
    backgroundColor: '#2563eb',
    color: 'white',
  },
  grayButton: {
    backgroundColor: '#d1d5db',
    color: '#1f2937',
  },
  defaultViewButton: {
    backgroundColor: '#f3f4f6',
    color: '#1f2937',
    border: '1px solid #d1d5db',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  instructionPanel: {
    padding: '1rem',
    backgroundColor: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    width: '100%',
    maxWidth: '28rem',
  },
  instructionTitle: {
    fontSize: '1.125rem',
    fontWeight: '600',
    marginBottom: '0.75rem',
  },
  instructionItems: {
    listStyleType: 'disc',
    paddingLeft: '1.25rem',
    lineHeight: '1.5',
  },
  instructionItem: {
    marginBottom: '0.25rem',
  },
  // Стили для модальных окон
  modal: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
  },
  modalContent: {
    backgroundColor: 'white',
    padding: '1.5rem',
    borderRadius: '0.5rem',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    width: '100%',
    maxWidth: '32rem',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  modalTitle: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    marginBottom: '1rem',
    position: 'relative',
  },
  modalCloseButton: {
    position: 'absolute',
    top: '-0.5rem',
    right: '-0.5rem',
    background: '#ef4444',
    color: 'white',
    border: 'none',
    borderRadius: '50%',
    width: '30px',
    height: '30px',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 2px 4px rgba(0,0,0,0.2)',
    transition: 'background-color 0.2s ease',
  },
  formGroup: {
    marginBottom: '1rem',
  },
  label: {
    display: 'block',
    color: '#374151',
    marginBottom: '0.5rem',
    fontWeight: '500',
  },
  input: {
    width: '100%',
    padding: '0.5rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.25rem',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    padding: '0.5rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.25rem',
    boxSizing: 'border-box',
    minHeight: '80px',
    resize: 'vertical',
  },
  radioGroup: {
    display: 'flex',
    gap: '1rem',
  },
  radioLabel: {
    display: 'flex',
    alignItems: 'center',
  },
  radioInput: {
    marginRight: '0.5rem',
  },
  selectedPerson: {
    padding: '0.5rem',
    backgroundColor: '#eff6ff',
    borderRadius: '0.25rem',
    border: '1px solid #bfdbfe',
  },
  modalButtons: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '0.5rem',
    marginTop: '1.5rem',
  },
  selectionModeNotice: {
    position: 'fixed',
    top: '1rem',
    left: '50%',
    transform: 'translateX(-50%)',
    padding: '0.5rem 1rem',
    borderRadius: '0.5rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
    zIndex: 50,
    maxWidth: '48rem',
    textAlign: 'center',
    color: 'white',
  },
  selectionModeTitle: {
    fontWeight: 'bold',
    marginBottom: '0.25rem',
  },
  selectionModeButton: {
    marginTop: '0.5rem',
    backgroundColor: 'white',
    color: '#1f2937',
    padding: '0.25rem 0.5rem',
    borderRadius: '0.25rem',
    border: 'none',
    cursor: 'pointer',
  },
  infoText: {
    fontSize: '12px',
    color: '#6b7280',
    marginTop: '0.5rem',
    fontStyle: 'italic',
  },
};

// Стили для узлов дерева
export const NODE_STYLES = {
  maleNode: {
    fill: '#e6f7ff',
    stroke: '#c2cfd6',
    strokeWidth: 2,
    transition: 'fill 0.3s, stroke 0.3s, stroke-width 0.3s, opacity 0.3s',
  },
  femaleNode: {
    fill: '#fff0f6',
    stroke: '#c2cfd6',
    strokeWidth: 2,
    transition: 'fill 0.3s, stroke 0.3s, stroke-width 0.3s, opacity 0.3s',
  },
  selectedMaleNode: {
    stroke: '#1890ff',
    transition: 'stroke 0.3s',
  },
  selectedFemaleNode: {
    stroke: '#eb2f96',
    transition: 'stroke 0.3s',
  },
  parentSelectionNode: {
    fill: '#d4f5d3',
    stroke: '#52c41a',
    transition: 'fill 0.3s, stroke 0.3s',
  },
  spouseSelectionNode: {
    fill: '#ffd6e7',
    stroke: '#eb2f96',
    transition: 'fill 0.3s, stroke 0.3s',
  },
  disabledNode: {
    fill: '#f5f5f5',
    stroke: '#d9d9d9',
    transition: 'fill 0.3s, stroke 0.3s',
  },
  nodeText: {
    fontFamily: 'Arial',
    fontSize: '13px',
    fontWeight: 'bold',
    textAnchor: 'middle',
    dominantBaseline: 'middle',
    transition: 'opacity 0.3s',
  },
  nodeSubText: {
    fontFamily: 'Arial',
    fontSize: '11px',
    fill: '#666',
    textAnchor: 'middle',
    dominantBaseline: 'middle',
    transition: 'opacity 0.3s',
  },
  connection: {
    stroke: '#8ca0b3',
    strokeWidth: 2,
    transition: 'opacity 0.5s, stroke-dasharray 0.5s',
  },
  nodeWithHiddenGen: {
    stroke: '#2563eb',
    strokeDasharray: '0',
    strokeWidth: 3,
    transition: 'stroke 0.3s, stroke-width 0.3s',
  },
  // Стили для кнопок на линиях
  lineToggleButton: {
    cursor: 'pointer',
    opacity: 0,
    transition: 'opacity 0.3s ease',
  },
  lineToggleButtonBackground: {
    fill: 'white',
    stroke: '#2563eb',
    strokeWidth: 2,
    filter: 'drop-shadow(0 2px 6px rgba(37, 99, 235, 0.25))',
  },
  lineToggleButtonIcon: {
    stroke: '#2563eb',
    strokeWidth: 2.5,
    strokeLinecap: 'round',
  },
  // Стили для индикации скрытого поколения
  hiddenIndicatorText: {
    fontSize: '12px',
    fill: '#666',
    fontStyle: 'italic',
    textAnchor: 'start',
    dominantBaseline: 'middle',
  },
  // Стили для иконки ветки родственника
  branchIcon: {
    cursor: 'pointer',
    opacity: 0,
    transition: 'opacity 0.3s ease',
  },
  branchIconVisible: {
    cursor: 'pointer',
    opacity: 1,
    transition: 'opacity 0.3s ease',
  },
  branchIconBackground: {
    fill: 'white',
    stroke: '#059669',
    strokeWidth: 2,
    filter: 'drop-shadow(0 2px 6px rgba(5, 150, 105, 0.25))',
  },
  branchIconBackgroundActive: {
    fill: '#059669',
    stroke: '#059669',
    strokeWidth: 2,
    filter: 'drop-shadow(0 2px 6px rgba(5, 150, 105, 0.4))',
  },
  branchIconTree: {
    stroke: '#059669',
    strokeWidth: 2,
    strokeLinecap: 'round',
    fill: 'none',
  },
  branchIconTreeActive: {
    stroke: 'white',
    strokeWidth: 2,
    strokeLinecap: 'round',
    fill: 'none',
  },
  // Стили для узлов при фильтрации по ветке
  filteredNode: {
    opacity: 0.3,
    transition: 'opacity 0.3s ease',
  },
  // Стили для модального окна с информацией о персоне
  personInfoModal: {
    display: 'flex',
    gap: '1rem',
  },
  personPhoto: {
    width: '120px',
    height: '120px',
    borderRadius: '8px',
    objectFit: 'cover',
    backgroundColor: '#f3f4f6',
    border: '2px solid #e5e7eb',
  },
  personDetails: {
    flex: 1,
  },
  personName: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
    marginBottom: '0.5rem',
  },
  personField: {
    marginBottom: '0.75rem',
  },
  fieldLabel: {
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#374151',
    marginBottom: '0.25rem',
  },
  fieldValue: {
    fontSize: '0.875rem',
    color: '#6b7280',
    lineHeight: '1.4',
  },
  // Стили для фото на карточке
  cardPhoto: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    objectFit: 'cover',
    backgroundColor: '#f3f4f6',
    border: '1px solid #e5e7eb',
  },
  defaultPhoto: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    backgroundColor: '#e5e7eb',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    color: '#9ca3af',
  },
};